package com.jitterted.ebp.blackjack.domain.assertj;

import com.jitterted.ebp.blackjack.domain.Card;

/**
 * {@link Card} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractCardAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class CardAssert extends AbstractCardAssert<CardAssert, Card> {

    /**
     * Creates a new <code>{@link CardAssert}</code> to make assertions on actual Card.
     *
     * @param actual the Card we want to make assertions on.
     */
    public CardAssert(Card actual) {
        super(actual, CardAssert.class);
    }

    /**
     * An entry point for CardAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myCard)</code> and get specific assertion with code completion.
     *
     * @param actual the Card we want to make assertions on.
     * @return a new <code>{@link CardAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static CardAssert assertThat(Card actual) {
        return new CardAssert(actual);
    }
}
